### PR TITLE
Lots of minor bugs squashed.

### LINKED ISSUE #202: Add latin script, utf-8 restriction to UG.

### LINKED ISSUE #208: [PE-D] Able to create assets/liabilities/policy with negative values
I was able to create assets with negative value. I was also able to do this for policies, liabilities and the commissions etc

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yongxiangng/ped#6

### LINKED ISSUE #209: [PE-D] Able to cause total asset value (or other accumulated values) to overflow
I was quite easily able to cause the accumulated value to overflow. Perhaps it would be better to either decrease the limit of each assets or increase the limit of the accumulator by using a larger datatype. This may not seem reasonable if we're talking USD, but some currencies have much larger denominations so i think it might be a valid concern

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yongxiangng/ped#7

### LINKED ISSUE #214: [PE-D] Cosmetic bug, unable to see table header fully
I think the team could decrease the width of policy name to make more space for the other columns. I did not intentionally resize my window to this size, it is about the default size

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: yongxiangng/ped#12

### LINKED ISSUE #217: [PE-D] Remove not working properly if using table sorting
`append n/Good Class Bungalow ty/Property v/$10000000 r/newly bought with bank loan`
sort asset name in order specified by picture above
`remove 1`
this removes GCB rather than asset name which isn't right base on the table (I understand it's hard and why this bug exist, maybe you should just disable the sorting feature, it doesn't add value IMO)

From your UserGuide:
```
Remove an existing asset from the current client you are viewing. You must be in the Assets tab.

    Removes the asset at the specified INDEX.
    The index refers to the index number shown in the displayed asset list.
    The index must be a positive integer 1, 2, 3, …​
```

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yongxiangng/ped#15

### LINKED ISSUE #231: [PE-D] Error message of bad `AppendCommand` input does not reflect the actual error
Left out type field for an asset

￼

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: zhenxuantan/ped#3

### LINKED ISSUE #232: [PE-D] "No." column header cannot be seen
The column header cannot be seen on a 13-inch MacBook Pro.

￼

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: zhenxuantan/ped#4

### LINKED ISSUE #238: [PE-D] Invalid emails are accepted
Emails can be added even if it is "ii@ii"

￼

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: zhenxuantan/ped#9

### PR DESCRIPTION
**Pull request by bharathcs**
### Use `BigInteger` to solve Money overflow in table. 42df9a3

Fixes #209

### Add proper message constraints for attributes. 9766666

Fixes #231

### Disable sorting for `AttributeTable` columns. 554fedc

Fixes #217

### Change column widths and default window size and hides index column header. 4a4cd45

Fixes #232
Fixes #214

- Note that the default window size is bigger to see all columns (may need to `gradlew clean` to see effect)

### Revert all negative support in `Money`. c410a96

Fixes #208

### Add FAQ to explain duplicate names & alternative scripts / currencies 6727150

Fixes #202
and adds in FAQ for users interested in multicurrency or annoyed at our
(module given) constraint against multiple people with the same name.

### Drop support for emails without TLD. 8497174

Reasoning:
emails without .com / .edu / etc are not accessible over the internet by any mail client. The typical example used is email@localhost, which obviously requires you to email to a local mail server.

This use case would not exist for our app catering to financial advisors keeping track of their clients.

Fixes #238

### CODE REVIEW

File: src/main/java/donnafin/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -240,25 +240,30 @@ public static Money parseMoney(String money) throws ParseException {
         String trimmedCommission = money.trim();
```
Comment (sheehui) [inline src/main/java/donnafin/logic/parser/ParserUtil.java:240]: We should give this variable a more appropriate name :). Not sure where commission comes in

File: src/main/java/donnafin/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -240,25 +240,30 @@ public static Money parseMoney(String money) throws ParseException {
...
+        try {
+            long value = Long.parseLong(decimalString.replace(".", ""));
             return new Money(value);
-        } else {
+        } catch (Money.MoneyException e) {
+            throw new ParseException(e.getMessage());
+        } catch (NumberFormatException e) {
             throw new ParseException(
-                    String.format("Input string '%s' does not match any monetary value format.", trimmedCommission));
+                    String.format("Input string '%s' exceeds maximum monetary value.", trimmedCommission));
```
Comment (sheehui) [inline src/main/java/donnafin/logic/parser/ParserUtil.java:266]: Should we leave a small explanation why it cannot be exceeded. maybe sth like SGD max can't be .....

File: docs/UserGuide.md [hunk 3]
```diff
@@ -352,6 +352,15 @@ If your changes to the data file makes its format invalid, DonnaFin will discard
 **Q**: How do I transfer my data to another Computer?<br>
 **A**: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous DonnaFin home folder.
 
+**Q**: I have multiple clients with the same name, but your application won't let me add them! What do I do?
+**A**: We realise some names are common, but we decided to prioritise your ability to instantly recognise a client over letting you keep the accuracy of the name. For that reason, we suggest adding other identifying nicknames or words in the name e.g. "John Walker (Bartender)" and "John Walker (Johnny)".
```
Comment (sheehui) [inline docs/UserGuide.md:356]: tbh im not very convinced by this since there may come a time where there are too many clients to keep track of their nicknames. but at the same time im not sure what else to do...

**Review by sheehui — COMMENTED** [review]
Wow so many issue fixes at once 🤩 good work!

File: src/main/java/donnafin/logic/parser/ParserUtil.java (hunk 1 above)
Comment (bharathcs) [reply src/main/java/donnafin/logic/parser/ParserUtil.java:240]: rekt. excellent point!

File: docs/UserGuide.md (hunk 3 above)
Comment (bharathcs) [reply docs/UserGuide.md:356]: Same but no choice right?

File: src/main/java/donnafin/logic/parser/ParserUtil.java (hunk 2 above)
Comment (bharathcs) [reply src/main/java/donnafin/logic/parser/ParserUtil.java]: I've tried, take a look!

**Review by sheehui — APPROVED** [review]
Very nice, how does it feel to close 8 issues at once? hehe
