### PR TITLE
valid command word in wrong window/tab shows appropriate error message

### LINKED ISSUE #150: Valid command word in wrong window/tab shows appropriate error message
now displays unknown command, while not wrong in context of where the client is, should not be categorised as unknown.

### PR DESCRIPTION
**Pull request by sheehui**
Fixes #150 

Currently, a valid command word in wrong window/tab throws an "unknown command" error. Which is not true. 

Thus, if user uses client window commands in home window, an appropriate message is shown and vice versa.

The same logic is applied to tabs as contacts tab accepts only edit. while assets, liabilities, policies tab accept only append and remove on top of those inherited from client parser. notes tab will not accept additional commands.

Note that this PR will likely impact @mrmrinal incoming tests.

### CODE REVIEW

**Comment by sheehui** [comment]
I noticed that there's a `NotesTabParser`. Given that we are not implementing a CLI for Notes we should remove it.

File: src/main/java/donnafin/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -49,6 +54,21 @@ public Command parseCommand(String commandWord, String arguments) throws ParseEx
         case HelpCommand.COMMAND_WORD:
             return !arguments.equals("") ? throwsInvalidInputMsg() : new HelpCommand();
 
+        case HomeCommand.COMMAND_WORD:
+            return !arguments.equals("") ? throwsInvalidInputMsg() : new HomeCommand();
```
Comment (Bluntsord) [inline src/main/java/donnafin/logic/parser/AddressBookParser.java:58]: Do u want this to be fallthrough as well and say that it is not possible. No point returning new home command in addressbookparser. Just brings it back to the same thing

**Review by Bluntsord — APPROVED** [review]
Looks nice! Left small comments to see cfm minor things. Feel free to merge after

File: src/main/java/donnafin/logic/parser/AddressBookParser.java (hunk 1 above)
Comment (sheehui) [reply src/main/java/donnafin/logic/parser/AddressBookParser.java:58]: I think it will be quite odd for home command to not be available here. Users can use it and yes, it does bring it back to the same thing but it feels more complete. Using home command would show the user they are already in home window. Since the displayed message is "Currently viewing home window.", the behaviour is still correct. What do you think?

Comment (bharathcs) [reply src/main/java/donnafin/logic/parser/AddressBookParser.java:58]: I think "Currently viewing home window" is the right response. Its lucky its not "Switching to viewing home" or smth like that. Thanks for exploring that avenue tho, tee chin.

**Review by bharathcs — APPROVED** [review]
Nice work! A really small thing: for files like `PolicyTabParser`, the switch case for edit (throwing a message to say its the wrong window), comes before the switch case for append and remove.  Putting edit at the end (I think this module calls it making the happy path more prominent) will improve readability, but its v v minor.

**Comment by bharathcs** [comment]
> I noticed that there's a `NotesTabParser`. Given that we are not implementing a CLI for Notes we should remove it.

our discussion for reference: We should still have it even if there is no logic in it. `ClientViewParser` is a an abstract class, and we still need a concrete implementation for to handle commands in the notes tab.

I see you've already done it anw 👍

**Comment by bharathcs** [comment]
wowie

**Review by bharathcs — APPROVED** [review]
Nice!
